package org.jboss.pnc.jshim.cli;

import java.util.concurrent.Callable;

import org.jboss.pnc.jshim.backend.constants.AutogeneratedConstants;

import picocli.CommandLine;

@CommandLine.Command(
        subcommands = { Tool.class, Info.class },
        name = AutogeneratedConstants.APP_NAME,
        description = AutogeneratedConstants.APP_DESCRIPTION,
        version = AutogeneratedConstants.BLENDED_VERSION,
        mixinStandardHelpOptions = true)
public class App implements Callable<Integer> {

    @CommandLine.Spec
    CommandLine.Model.CommandSpec spec;

    @Override
    public Integer call() {
        // if the command was invoked without subcommand, show the usage help
        spec.commandLine().usage(System.err);
        return 0;
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }
}