package org.jboss.pnc.jshim.constants;

/**
 * The values in here are auto-generated from Maven plugin maven-replacer-plugin and the template is found in the
 * template folder
 *
 * @author Dustin Kut Moy Cheung <dcheung@redhat.com>
 */
public final class AutogeneratedConstants {

    public static final String APP_NAME = "@name@";
    public static final String APP_DESCRIPTION = "@description@";

    public static final String VERSION = "@version@";
    public static final String COMMIT_HASH = "@commit-id@";
    public static final String BUILD_TIME = "@build-time@";
    public static final String BLENDED_VERSION = "@version@ (commit: @commit-id@, built on @build-time@)";
}

